export const name_list = [
  "Tan Lee Peng ",
  "Liow Nyet Lin ",
  "Liow Num Nyet",
  "Tai Nyok Yong",
  "Yen Shu Ming ",
  "Tan Gaik Lian ",
  "Ivy Liau",
  "Abigail Lim",
  "Kelly Saw",
  "Moey Sook Fun ",
  "Wee Mooi Kiew",
  "Cho Chee Heng ",
  "Teoh Chiew Leng",
  "Annabelle Xiang Ping Teo",
  "Emilio Kennedy",
  "Jennifer Foo Hui Chen",
  "Tan Chee Eng ",
  "Liew Kui Yong ",
  "Ho Wei Loon",
  "Ku Soik Nee",
  "Aaron Lim Fang Weng ",
  "Serene Lim",
  "Samantha Geh",
  "Jennifer Ong",
  "Peter Yong",
  "Lua Yik Chung ",
  "Michelle Lua Kim Geot",
  "Suzilah Binti Zainuddin ",
  "Cho Wenqi ",
  "Cho Yangxuan ",
  "Raja Nazrul Izzat Bin Raja Ismail",
  "Khonteesa Binti Kamarul Ariffin",
  "Kam Shih Sing ",
  "Ho Wee Ming",
  "Oh Chai Ying",
  "Chang Heap Kit",
  "Saw Mei Ling ",
  "Juliet Tiong Yong Yong ",
  "Lau Hung Ping",
  "Ong Zhao Di ",
  "Yap Chee Yuan",
  "Edwin Ee Xin Yun",
  "Lim Siew Moi",
  "Ng Cha Beng ",
  "Yong Chyang An",
  "Tan Puei Ling ",
  "Audrey Loh May Jin",
  "Janice Foon Hui Min ",
  "Wong Pei Zhi",
  "Boon Choo Moi ",
  "Tey Lee Chook",
  "Shamino Tey",
  "Chua Teik Min ",
  "Yong Sze Zhao",
  "Khor Kim Bu ",
  "Koay Ying Ying",
  "Lau Siew Eng ",
  "Khor Khai Wei",
  "Lim Tatt Boon ",
  "Ow Yong Tan Ling",
  "Lim Jen Sen",
  "Lim Yu Zen",
  "Sharizal Bin Sarif",
  "Tan Chen Yuan",
  "Lua Kim Chu ",
  "Lim Hai Ping",
  "Manogaran S/O P A Devanathan ",
  "Ching Chui Lang",
  "Tan Sock Bin ",
  "Lim Eng Theam",
  "Teoh Peng Seng ",
  "Tan Lee Lee",
  "Tong Leung Fatt ",
  "Yeoh Guat Poh ",
  "Ebby Loo",
  "Peh Chwee Ping",
  "Yap Foong Lin ",
  "Lee Boon Kian",
  "Jordan Poon Chee Hoong",
  "Cissy Saw Soik Ling",
  "Ho Sok Ha ",
  "Chong Jia Wun",
  "Lee Kok Kit ",
  "Then Cheong Lim ",
  "Kng Bee Lan",
  "Vivien Ooi Pek Sim ",
  "Chea Moon Sing ",
  "Tan Thian Teng ",
  "Lim Joo See ",
  "Chor Kin Keong",
  "Too Wei Ann ",
  "Tan Yeat Kheng ",
  "Gan Leh Boon",
  "Lee Lay Hui ",
  "Lim Wee Tek",
  "Chan Wee Siong ",
  "Fun Choon Yin ",
  "Lei Keat Han ",
  "Tong Man Loong ",
  "Nur Elizdawati Binti Dahlan ",
  "Goh Beng Chiang ",
  "Lee Chee Wan ",
  "See Tah Shyan ",
  "Hartmann Thomas ",
  "Jocelyn Goh Lyn Chu ",
  "Ian Looi",
  "Har Wai Meng ",
  "Ting Huey Sheng ",
  "Tee Choun Zhi ",
  "Ting Chun Lin ",
  "Sherene Wong",
  "Hwee Teen",
  "Kobe Yap",
  "Ronnie Lim",
  "Vincent Yap",
  "Tan Jin Hui ",
  "Fang Chee Hua ",
  "Theah Fong Wan ",
  "Chan Weng Yern",
  "Wong Kam Hai",
  "Poovendran A/L Balakrishnan ",
  "Low Wei Hean ",
  "Tan Chee San",
  "Koh Zian Hung",
  "Ng Jia Ying",
  "Chew Tzyy Wey",
  "Tan Lit Siang ",
  "Mong Chiu Yen",
  "Dominic Ng Kah Leong ",
  "Esther Lim Siew Hui",
  "Nurul Sobah Binti Mohd Yasin ",
  "Ng Por Lin ",
  "Tham Guan Min",
  "Krystal Ann Tan Zhi Ling ",
  "Lee Yin Sin ",
  "Kwok Siew Yoong",
  "Lee Boon Ching ",
  "Soh Bee Lian",
  "Teo Chee Li ",
  "Sandy Wong Hui Xian",
  "Tan Hon Jie ",
  "Yap Tit Sinn ",
  "Teoh Kak Gee",
  "Tan Fei Sian",
  "Ng Yu Jin",
  "Wong Quan ",
  "Chong Wan Qing",
  "Ng Chin Wai ",
  "Tan Kai Yan",
  "Ng Kelly",
  "Ng Chen Chow",
  "Chong Yu Chen ",
  "Wong Siew Hui ",
  "Joel See Yue Jian ",
  "Chloe Goh Hui Ju",
  "Yap Yong Loon",
  "Lee Wai Khey",
  "Mervyn Low Tian Shian ",
  "Priscilla Lim Mei Lian",
  "Pui Yit Hong",
  "Bianca Ng Sze Cay",
];
